name: Test

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        if type sudo >/dev/null 2>&1; then SUDO="sudo"; else SUDO=""; fi
        sudo ./install-deps

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCI_BUILD=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE --output-on-failure

    - name: Install
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        if type sudo >/dev/null 2>&1; then SUDO="sudo"; else SUDO=""; fi
        $SUDO cmake --build . --target install --config $BUILD_TYPE
